version: '3'

services:
    php5.5:
      image: mesa/oxid:php5.5
      restart: always
      container_name: oxid_php5.5
      ports:
        - "8083:80"
      volumes:
        - ./src/:/data/
      links:
        - oxid_db
      environment:
        MYSQL_HOST: oxid_db
        MYSQL_DATABASE: oxid
        MYSQL_USER: oxid
        MYSQL_PASSWORD: oxid
        OXID_SHOP_URL: "http://localhost:8083"
        OXID_IDEBUG: 0
        OXID_ADMIN_PASSWORD: oxid
        OXID_ADMIN_USERNAME: oxid

    php5.6:
      image: mesa/oxid:php5.6
      restart: always
      container_name: oxid_php5.6
      ports:
        - "8082:80"
      volumes:
        - ./src/:/data/
      links:
        - oxid_db
      environment:
        MYSQL_HOST: oxid_db
        MYSQL_DATABASE: oxid
        MYSQL_USER: oxid
        MYSQL_PASSWORD: oxid
        OXID_SHOP_URL: "http://localhost:8082"
        OXID_IDEBUG: 0
        OXID_ADMIN_PASSWORD: oxid
        OXID_ADMIN_USERNAME: oxid

    php7.0:
      image: mesa/oxid:php7.0
      restart: always
      container_name: oxid_php7.0
      ports:
        - "8081:80"
      volumes:
        - ./src/:/data/
      links:
        - oxid_db
      environment:
        MYSQL_HOST: oxid_db
        MYSQL_DATABASE: oxid
        MYSQL_USER: oxid
        MYSQL_PASSWORD: oxid
        OXID_SHOP_URL: "http://localhost:8081"
        OXID_IDEBUG: 0
        OXID_ADMIN_PASSWORD: oxid
        OXID_ADMIN_USERNAME: oxid
        PHP_ERROR_REPORTING: -1

    oxid_db:
      image: mesa/oxid:db
      restart: always
      container_name: oxid_db
      ports:
        - "3306:3306"
      volumes:
#       - ./oxid_db:/var/lib/mysql
    # Mount your DB dumps here
        - ./db-dumps/:/docker-entrypoint-initdb.d/
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: oxid
        MYSQL_USER: oxid
        MYSQL_PASSWORD: oxid

