# This is only the composer build file used by the automated build process for dockerhub
#
# for a real example see demo/docker-compose.yml
version: '2'
services:
    oxid:
        build: ./
        container_name: oxid
        ports:
            - "80:80"
        volumes:
            - "/etc/localtime:/etc/localtime"
        environment:
            MYSQL_HOST: oxid_db
